# Generated by Django 4.2.1 on 2023-05-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito_app', '0002_producto_delete_tienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='color',
            new_name='envio',
        ),
    ]
